# Build NodeJS Express app using Azure Pipelines
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: ls
    displayName: 'current dir'
  - script: mkdir myprj
  - script: ls
    displayName: 'myprj dir'
  - script: |
      cd myprj;
      cmake ..;
    displayName: 'cmake'
  - script: make
    displayName: 'make'