# Build NodeJS Express app using Azure Pipelines
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo dir
    displayName: 'current dir'
  - script: mkdir myprj
  - script: cd myprj
  - script: echo dir
    displayName: 'myprj dir'
  - script: cmake ..
    displayName: 'cmake'
  - script: make
    displayName: 'make'