resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: 
  - Cmd
  - msbuild
  - visualstudio

steps:
- task: BatchScript@1
  displayName: 'Run script mycmake.bat'
  inputs:
    filename: mycmake.bat
    arguments: '$(githubtoken)'


- task: GithubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
   githubConnection: azureSubscription
   repositoryName: makefriend8/Azure_Pipelines_test_c