# Build NodeJS Express app using Azure Pipelines
jobs:
- job: Windows
  resources:
  - repo: self
  queue:
    name: Hosted VS2017
    demands: 
    - Cmd
    - msbuild
    - visualstudio
  steps:
  - task: BatchScript@1
    displayName: 'Run script mycmake.bat'
    inputs:
      filename: mycmake.bat
      arguments: '$(githubtoken)'
  - task: VSBuild@1
    displayName: 'Build solution **\*.sln'
    inputs:
      solution: '$(Parameters.solution)'

      platform: '$(BuildPlatform)'

      configuration: '$(BuildConfiguration)'