# Build NodeJS Express app using Azure Pipelines
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: bash mybuild.sh
    displayName: 'cmake'
  - script: make
    displayName: 'make'