# Build NodeJS Express app using Azure Pipelines
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
    displayName: 'only test'
  - script: mkdir myprj
  - script: cd myprj
  - script: cmake ..
  - script: make