# Build NodeJS Express app using Azure Pipelines
variables:
  the_token: $(githubtoken)

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: bash mybuild.sh $(the_token)
    displayName: 'cmake'
  - script: ls myprj
    displayName: 'myprj content'
  - script: ls
    displayName: 'current content'
  - task: GithubRelease@0
    displayName: 'Create GitHub Release'
    inputs:
     githubConnection: github.com_makefriend8
     repositoryName: makefriend8/Azure_Pipelines_test_c
     action: edit
     Tag: ReleaseLinux
     assets: $(Build.Repository.LocalPath)/myprj/Tutorial-1.0.1-Linux.*
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo hello from macOS
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: BatchScript@1
    displayName: 'Run script mycmake.bat'
    inputs:
      filename: mycmake.bat
      arguments: '$(githubtoken)'
  - task: GithubRelease@0
    displayName: 'Create GitHub Release'
    inputs:
     githubConnection: github.com_makefriend8
     repositoryName: makefriend8/Azure_Pipelines_test_c
     action: edit
     Tag: ReleaseWindows
     assets: $(Build.Repository.LocalPath)/myprjwindows/*.exe